#!/usr/bin/env bash
source .env.test

setup() {
  ./kc-client-add $TEST_CLIENT_ID > /dev/null
}
# teardown() {
#   ./kc-client-del $TEST_CLIENT_ID
# }

test_delete_client_by_uuid() {
  # TEST: default query first 20 itens
  client_uuid=$(./kc-client-query $TEST_CLIENT_ID | yq --null-input '.[0].id | select( . != null )')
  
  if [ ! "$client_uuid" ]; then
    fail "Client id '$TEST_CLIENT_ID' MUST BE REGISTRED!"
  fi

  ./kc-client-del $client_uuid
}

test_delete_client_by_url() {
  # TEST: default query first 20 itens
  client_uuid=$(./kc-client-query $TEST_CLIENT_ID | yq --null-input '.[0].id | select( . != null )')
  
  if [ ! "$client_uuid" ]; then
    fail "Client id '$TEST_CLIENT_ID' MUST BE REGISTRED!"
  fi

  ./kc-client-del "${KC_REALM_URL}/clients/$client_uuid"
}
