#!/usr/bin/env bash
source .env.test

setup() {
  ./kc-client-add $TEST_CLIENT_ID > /dev/null
}
teardown() {
  CLIENT_UUID=$(./kc-client-query $TEST_CLIENT_ID | yq --null-input '.[0].id | select( . != null )')
  ./kc-client-del $CLIENT_UUID # > /dev/null
}

test_edit_client() {
  # TEST: default query first 20 itens
  # CLIENT_DATA=$(yq -o json ".keycloak[$i].clientRepresentation" ../.azuredevops/config/development/keycloak.yml)
  client_uuid=$(./kc-client-query $TEST_CLIENT_ID | yq --null-input '.[0].id | select( . != null )')
  
  if [ ! "$client_uuid" ]; then
    fail "Client id '$TEST_CLIENT_ID' MUST BE REGISTRED!"
  fi

  CLIENT_DATA="{\"id\": \"$client_uuid\", \"description\": \"DDDDD\"}"
  ./kc-client-edit "${KC_REALM_URL}/clients/$client_uuid" "$CLIENT_DATA"
}
