#!/usr/bin/env bash
source .env.test

setup() {
  ./kc-client-add $TEST_CLIENT_ID > /dev/null
  
  CLIENT_UUID=$(./kc-client-query $TEST_CLIENT_ID | yq --null-input '.[0].id | select( . != null )')
  ./kc-client-role-add $CLIENT_UUID $TEST_ROLE_NAME > /dev/null
}

teardown() {
  CLIENT_UUID=$(./kc-client-query $TEST_CLIENT_ID | yq --null-input '.[0].id | select( . != null )')
  ./kc-client-del $CLIENT_UUID > /dev/null
}

test_delete_role_by_uuid() {
  # TEST: default query first 20 itens
  CLIENT_UUID=$(./kc-client-query $TEST_CLIENT_ID | yq --null-input '.[0].id | select( . != null )')
  ROLE_UUID=$(./kc-client-role-query $CLIENT_UUID $TEST_ROLE_NAME | yq --null-input '.[0].id | select( . != null )')
  
  if [ ! "$ROLE_UUID" ]; then
    fail "Role id '$TEST_ROLE_NAME' MUST BE REGISTRED!"
  fi

  ./kc-client-role-del $ROLE_UUID
}
