#!/usr/bin/env bash
source ./.env.test

test_should_print_query_with_default_values() {
  # TEST: default query first 20 itens
  # ./kc-client-query | yq '.[] |= pick(["id"])'
  LEN=$(./kc-client-query | yq '. | length()')
  [[ $LEN -gt 20 ]] && assert_equals "20" $LEN
  [[ $LEN -lt 21 ]] && assert_equals "20" "20"
}

test_should_print_query_with_max_2_values() {
  # TEST: default query first 20 itens
  assert_equals "2" "$(MAX=2 ./kc-client-query | yq '. | length()')"
}
