#!/bin/bash
source ./kc-token

[[ "$1" =~ ^https?$ ]] && CLIENT_URL=$1
[[ "$1" =~ ^[a-z0-9-]+$ ]] && CLIENT_URL="${KC_REALM_URL}/clients/$1"

CLIENT_EDIT_RESULT=$(curl -s --request DELETE \
  --url ${CLIENT_URL} \
  --header "Authorization: Bearer ${KC_ACCESS_TOKEN}"
)

echo -n $CLIENT_EDIT_RESULT

