#!/usr/bin/env bash
source .env.test

setup() {
  CLIENT_UUID=$(./kc-client-query $TEST_CLIENT_ID | yq --null-input '.[0].id | select( . != null )')
  ./kc-client-del $CLIENT_UUID > /dev/null
}
teardown() {
  CLIENT_UUID=$(./kc-client-query $TEST_CLIENT_ID | yq --null-input '.[0].id | select( . != null )')
  ./kc-client-del $CLIENT_UUID > /dev/null
}

test_add_new_client() {
  # TEST: default query first 20 itens
  CLIENT_UUID=$(./kc-client-query $TEST_CLIENT_ID | yq --null-input '.[0].id | select( . != null )')

  if [ "$CLIENT_UUID" ]; then
    # ./kc-client-query $client_id
    fail "Client id '$TEST_CLIENT_ID' already exists!"
  fi

  client_url=$(./kc-client-add $TEST_CLIENT_ID)
  assert_not_equals "" client_url
  ./kc-client-del $client_url
}
